permissionset 50060 "SBC Order Export"
{
    Assignable = true;
    Permissions = tabledata "SBCOE Export"=RIMD,
        tabledata "SBCOE Export Column"=RIMD,
        tabledata "SBCOE Export Definition"=RIMD,
        tabledata "SBCOE Export Email Group"=RIMD,
        tabledata "SBCOE Export Email List"=RIMD,
        tabledata "SBCOE Export Entry"=RIMD,
        tabledata "SBCOE Export Options"=RIMD,
        tabledata "SBCOE Export Row"=RIMD,
        tabledata "SBCOE Export Send Log"=RIMD,
        table "SBCOE Export"=X,
        table "SBCOE Export Column"=X,
        table "SBCOE Export Definition"=X,
        table "SBCOE Export Email Group"=X,
        table "SBCOE Export Email List"=X,
        table "SBCOE Export Entry"=X,
        table "SBCOE Export Options"=X,
        table "SBCOE Export Row"=X,
        table "SBCOE Export Send Log"=X,
        report "SBCOE Copy Export Definition"=X,
        report "SBCOE Export Wrapper"=X,
        codeunit "SBCOE Email Events"=X,
        codeunit "SBCOE Email Log Events"=X,
        codeunit "SBCOE Email Recipient Helper"=X,
        codeunit "SBCOE Error Helper"=X,
        codeunit "SBCOE Excel Buffer Events"=X,
        codeunit "SBCOE Export Management"=X,
        page "SBCOE Email Group"=X,
        page "SBCOE Email Groups"=X,
        page "SBCOE Email List Part"=X,
        page "SBCOE Export"=X,
        page "SBCOE Export Archive"=X,
        page "SBCOE Export Column Part"=X,
        page "SBCOE Export Definition"=X,
        page "SBCOE Export Definitions"=X,
        page "SBCOE Export Entries Part"=X,
        page "SBCOE Export Options"=X,
        page "SBCOE Export Row Part"=X,
        page "SBCOE Export Send Log"=X,
        page "SBCOE Export Sends Part"=X;
}