/// <summary>
/// Default SBC Trade Allocation permissionset (ID 50200).
/// </summary>
permissionset 50200 "SBC Trade Allocation"
{
    Access = Internal;
    Assignable = true;
    Caption = 'SBC Trade Allocation', Locked = true;

    Permissions =
         table "SBCTA Detailed Trade Ledger" = X,
         tabledata "SBCTA Detailed Trade Ledger" = RIMD,
         table "SBCTA Indirect COGs Ledger" = X,
         tabledata "SBCTA Indirect COGs Ledger" = RIMD,
         table "SBCTA Indirect Posting Setup" = X,
         tabledata "SBCTA Indirect Posting Setup" = RIMD,
         table "SBCTA Tr. Budget Ledger Entry" = X,
         tabledata "SBCTA Tr. Budget Ledger Entry" = RIMD,
         table "SBCTA Trade Accrual Header" = X,
         tabledata "SBCTA Trade Accrual Header" = RIMD,
         table "SBCTA Trade Accrual Line" = X,
         tabledata "SBCTA Trade Accrual Line" = RIMD,
         table "SBCTA Trade Budget" = X,
         tabledata "SBCTA Trade Budget" = RIMD,
         table "SBCTA Trade Budget Options" = X,
         tabledata "SBCTA Trade Budget Options" = RIMD,
         table "SBCTA Trade Budget Rate Codes" = X,
         tabledata "SBCTA Trade Budget Rate Codes" = RIMD,
         table "SBCTA Trade Budget Rates" = X,
         tabledata "SBCTA Trade Budget Rates" = RIMD,
         table "SBCTA Trade Budget Setup" = X,
         tabledata "SBCTA Trade Budget Setup" = RIMD,
        table "STA Bracket Price" = X,
        tabledata "STA Bracket Price" = RMID,
        table "STA Bracket Price Code" = X,
        tabledata "STA Bracket Price Code" = RMID,
        table "STA Bracket Price Ledger" = X,
        tabledata "STA Bracket Price Ledger" = RMID,
         codeunit "SBCTA Buffer Expansion" = X,
         codeunit "SBCTA COGs Preview Events" = X,
         codeunit "SBCTA Customer Events" = X,
         codeunit "SBCTA Dimension Check Handler" = X,
         codeunit "SBCTA Item Events" = X,
         codeunit "SBCTA Preview Posting Events" = X,
         codeunit "SBCTA Purch Item Events" = X,
         codeunit "SBCTA Trade Accrual Mgmt." = X,
         codeunit "SBCTA Trade Ledger Mgmt." = X,
        codeunit "STA Bracket Price Events" = X,
         page "SBCTA Archived Budgets" = X,
         page "SBCTA Indirect COGs Ledger" = X,
         page "SBCTA Indirect COGs Preview" = X,
         page "SBCTA Indirect Posting Setup" = X,
         page "SBCTA Indirect Posting Subform" = X,
         page "SBCTA Tr. Budget Ledger Entry" = X,
         page "SBCTA Trade Accrual" = X,
         page "SBCTA Trade Accrual Lines" = X,
         page "SBCTA Trade Accruals" = X,
         page "SBCTA Trade Budget" = X,
         page "SBCTA Trade Budget Options" = X,
         page "SBCTA Trade Budget Rate Codes" = X,
         page "SBCTA Trade Budget Rates" = X,
         page "SBCTA Trade Budgets" = X,
         page "SBCTA Trade Budget Setup" = X,
         page "SBCTA Trade Ledger Preview" = X,
         page "SBCTA Trade Posting Subform" = X,
         report "SBCTA Copy & Archive Budget" = X,
         report "SBCTA Create Accrual & Credits" = X,
         report "SBCTA Create Accrual Credits" = X,
         report "SBCTA Create Ind. COGs Acc." = X,
         report "SBCTA Create Purch COGs" = X,
         report "SBCTA Create Trade Accruals" = X,
         report "SBCTA Create Trade Ledger" = X,
         report "SBCTA Delete Orphaed Accrual" = X,
         report "SBCTA Recalculate Budget Spend" = X;
}